version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:11
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASS}

volumes:
  postgres:
