version: '3'

services:
  postgres:
    container_name: bx-postgres
    image: postgres:11
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bossabox
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker

  mongo:
    container_name: bx-mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db

  redis:
    container_name: bx-redis
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

volumes:
  postgres:
  mongo:
  redis:
